### ISSUE TITLE
请问支持 根据颜色数值，指示点指定到到颜色秒

### ISSUE THREAD

**Issue by xuhongv** [KirisakiAria/we-color-picker#5]
请问支持 根据颜色数值，指示点指定到到颜色秒

**Comment by MakerGYT** [comment]
可以试下[mini-color-picker](https://github.com/MakerGYT/mini-color-picker)
![mini-color-picker](https://imgkr.cn-bj.ufileos.com/dcb57311-2305-4f47-b8f8-4cdf3e824c9e.gif)

**Comment by xuhongv** [comment]
@MakerGYT 牛逼
